### ISSUE TITLE
List items can't be moved down by hitting `Enter` when at the beginning of the line

### ISSUE THREAD

**Issue by richardsc** [mcgraths/todo.tab#1]
Hi, great extension -- thanks!

A UI thing that I find weird is that you can't move list items down by hitting enter while at the beginning of a line -- you have to hit enter when the cursor is anywhere on the line above it. This isn't too big of a deal, but it does mean that the only way to "bump" the first list item down is to cut/paste it to a new location.

Relatedly, as someone who writes in Markdown normally, it would be great if the `Display Markdown` mode allowed editing (i.e. in plain text).

**Comment by mcgraths** [comment]
Thanks Clark! Great feedback and it's something that has bothered me a bit as well. We'll definitely be adding this soon.

**Comment by mcgraths** [comment]
Just pushed some changes for Enter key issue if you wanted to download and run the dev build.

**Comment by richardsc** [comment]
Great, thanks!
